### ISSUE TITLE
weather.js data.main undefined

### ISSUE THREAD

**Issue by theMackabu** [sadparadiseinhell/tea-green#1]
![image](https://user-images.githubusercontent.com/32078755/99864092-551bd000-2b56-11eb-99eb-a19740350cfc.png)
current weather with api key will not function as `data.main` on line 60 is undefined

![image](https://user-images.githubusercontent.com/32078755/99864111-6ebd1780-2b56-11eb-8c7c-0a5bb0fd2f1e.png)

**Comment by theMackabu** [comment]
line in question `celcius = Math.round(parseFloat(data.main.temp)-273.15);`

**Comment by sadparadiseinhell** [comment]
Everything worked fine with my old key, but when I generated a new one, I got the same error as yours.
But after ~20 minutes everything started working again.
The problem was that the key was not activated immediately, you need to wait a little.

![rsz_5fb9014a6aad0](https://user-images.githubusercontent.com/17481484/99876855-691d0b80-2c02-11eb-8cab-876668dd510d.png)

**Comment by theMackabu** [comment]
Ok, thanks
